version: 0.2

env:
  variables:
    METRICS_API: "http://44.220.53.248:8000/api/generic-metrics/push/"  # <- change this!

phases:
  install:
    commands:
      - echo Installing Python dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running Django checks...
      - python manage.py check
  build:
    commands:
      - echo "Starting timed build and tests..."
      - START_TS=$(date +%s)
      # run migrations just to ensure DB schema OK
      - python manage.py migrate --noinput
      # run tests (even if 0 tests, still OK)
      - python manage.py test || true
      - END_TS=$(date +%s)
      - BUILD_TIME=$((END_TS-START_TS))
      - echo "Build+Test duration (sec): $BUILD_TIME"

      # Fake generic metrics - enough for your screenshots
      - PIPELINE_TOOL="aws-codepipeline"
      - PIPELINE_NAME="Generic-AWS-Pipeline"
      - TOTAL_TESTS=10
      - FAILED_TESTS=2
      - COVERAGE=78.5

      - |
        cat <<EOF > metrics_payload.json
        {
          "tool": "$PIPELINE_TOOL",
          "pipeline_name": "$PIPELINE_NAME",
          "build_time_sec": $BUILD_TIME,
          "tests_total": $TOTAL_TESTS,
          "failed_tests": $FAILED_TESTS,
          "coverage_percent": $COVERAGE
        }
        EOF

      - echo "Sending metrics to dashboard..."
      - cat metrics_payload.json
      - curl -X POST "$METRICS_API" \
          -H "Content-Type: application/json" \
          -d @metrics_payload.json || echo "Metrics push failed (but build will still finish)."

artifacts:
  files:
    - '**/*'
